# Generated by Django 5.0.1 on 2024-01-30 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_driver_passenger_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.driver'),
        ),
    ]
