# Generated by Django 5.0.1 on 2024-02-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_service_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_plate',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
